name: haskoin-node
version: 0.5.2
synopsis: Haskoin Node P2P library for Bitcoin and Bitcoin Cash
description: Bitcoin and Bitcoin Cash peer-to-peer protocol library featuring headers-first synchronisation.
category: Bitcoin, Finance, Network
author: Jean-Pierre Rupp
maintainer: xenog@protonmail.com
license: PublicDomain
license-file: UNLICENSE
github: haskoin/haskoin.git
homepage: http://github.com/haskoin/haskoin#readme
bug-reports: http://github.com/haskoin/haskoin/issues
extra-source-files:
  - README.md
  - CHANGELOG.md
dependencies:
  - base >=4.7 && <5
  - bytestring
  - cereal
  - haskoin-core
  - nqe
  - monad-logger
  - mtl
  - network
  - random
  - rocksdb-haskell
  - unliftio
library:
  source-dirs: src
  exposed-modules:
    - Network.Haskoin.Node
    - Network.Haskoin.Node.Common
  dependencies:
    - conduit
    - conduit-extra
    - hashable
    - time
    - unique
    - resourcet
    - rocksdb-query
    - string-conversions
tests:
  haskoin-node-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskoin-node
      - hspec
