name: haskoin-node
version: 0.9.13
synopsis: Haskoin Node P2P library for Bitcoin and Bitcoin Cash
description: Bitcoin and Bitcoin Cash peer-to-peer protocol library featuring headers-first synchronisation.
category: Bitcoin, Finance, Network
author: Jean-Pierre Rupp
maintainer: xenog@protonmail.com
license: PublicDomain
license-file: UNLICENSE
github: haskoin/haskoin.git
homepage: http://github.com/haskoin/haskoin#readme
bug-reports: http://github.com/haskoin/haskoin/issues
extra-source-files:
  - README.md
  - CHANGELOG.md
dependencies:
  - base >=4.9 && <5
  - bytestring
  - cereal
  - conduit
  - conduit-extra
  - containers
  - data-default
  - hashable
  - haskoin-core
  - monad-logger
  - mtl
  - network
  - nqe
  - random
  - resourcet
  - rocksdb-haskell
  - rocksdb-query
  - string-conversions
  - text
  - transformers
  - time
  - unliftio
  - unordered-containers
library:
  source-dirs: src
tests:
  spec:
    main: Spec.hs
    source-dirs: test
    verbatim:
      build-tool-depends:
          hspec-discover:hspec-discover
    dependencies:
      - hspec
      - haskoin-node
      - HUnit
      - safe
