resolver: lts-16.0
nix:
  packages:
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
extra-deps:
  - nqe-0.6.3
  - haskoin-core-0.15.0
  - secp256k1-haskell-0.4.0
  - github: jprupp/rocksdb-haskell
    commit: cf0d42018452a0ba3dd38eda7a0e6a3b498bbb1d
  - rocksdb-query-0.4.2
