resolver: lts-12.5
extra-deps:
- git: https://github.com/haskoin/haskoin-core.git
  commit: 843596abea9f46e4eed5fd7a69638b9b10a9398e
- git: https://github.com/xenog/nqe.git
  commit: c663fabb2f197f7db49ccbc1361150cd13c1f553
- rocksdb-haskell-1.0.1
- murmur3-1.0.3
- secp256k1-0.5.3
