resolver: lts-12.7
nix:
  packages:
    - autoconf
    - automake
    - cacert
    - libtool
    - rocksdb
    - secp256k1
    - zlib
extra-deps:
- git: https://github.com/haskoin/haskoin-core.git
  commit: c3c446900cb562a627061959f9a60ce8385e029e
- git: https://github.com/xenog/nqe.git
  commit: 43661fd297bd2e8d1ab61e7a9cf8030130b7e82e
- git: https://github.com/xenog/rocksdb-query.git
  commit: e34aca0fe90264dd9aa62d0e081e6e7f4e3a8559
- rocksdb-haskell-1.0.1
- murmur3-1.0.3
- secp256k1-1.1.0
