resolver: lts-16.0
nix:
  packages:
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
extra-deps:
  - github: jprupp/nqe
    commit: acbed8c6f39055b33e9c24de3ce634cfc2d8de88
  - github: haskoin/haskoin-core
    commit: d313ac58b2f22fa7570a5e1234244b7249a48382
  - github: haskoin/secp256k1-haskell
    commit: 239159122cc6f830957759a1d247ded7ffeba915
  - github: jprupp/rocksdb-haskell
    commit: 7bc824e8d07ed5a776735caae0b52fc1edf7286d
  - github: jprupp/rocksdb-query
    commit: b1a6f9a5e44f21d641f4b9343329e194ef6be6ba
