resolver: lts-12.9
nix:
  packages:
    - rocksdb
    - secp256k1
    - zlib
extra-deps:
  - rocksdb-haskell-1.0.1
  - murmur3-1.0.3
  - secp256k1-haskell-0.1.2
  - nqe-0.5.0
  - github: haskoin/haskoin-core
    commit: 61e01c092fc1c1023da1212de6db61fc5e3a0494
  - github: xenog/rocksdb-query
    commit: ffba9ee46d9aba19b96eb16c685d99df1c66ce04
