resolver: lts-16.22
nix:
  packages:
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
extra-deps:
  - nqe-0.6.3
  - haskoin-core-0.17.2
  - secp256k1-haskell-0.5.0
  - rocksdb-haskell-jprupp-2.1.2
  - rocksdb-query-0.4.2
