resolver: lts-17.7
nix:
  packages:
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
extra-deps:
  - git: https://github.com/haskoin/haskoin-core.git
    commit: 73fcd3c401ab38995802b4ccf9e2043eb00b6ff2
