resolver: lts-12.7
nix:
  packages:
    - autoconf
    - automake
    - cacert
    - libtool
    - rocksdb
    - zlib
extra-deps:
- git: https://github.com/haskoin/haskoin-core.git
  commit: 172b6bba317b6f87a7d569b95b9e0ea3917377d8
- git: https://github.com/xenog/nqe.git
  commit: 43661fd297bd2e8d1ab61e7a9cf8030130b7e82e
- git: https://github.com/xenog/rocksdb-query.git
  commit: e34aca0fe90264dd9aa62d0e081e6e7f4e3a8559
- rocksdb-haskell-1.0.1
- murmur3-1.0.3
- secp256k1-0.5.3
