resolver: lts-17.4
nix:
  packages:
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
extra-deps:
  - git: https://github.com/haskoin/haskoin-core.git
    commit: 46112458f58ecc56b2c14dace7caebe00888ebd4
