resolver: lts-12.5
nix:
  enable: true
  packages:
    - autoconf
    - automake
    - cacert
    - libtool
    - rocksdb
    - zlib
extra-deps:
- git: https://github.com/haskoin/haskoin-core.git
  commit: 8fdcabcf2eed8ba57490255c83a13123147f5d5d
- git: https://github.com/xenog/nqe.git
  commit: d93eebf1cce5fd58079be587dee78b50455e2a9c
- git: https://github.com/xenog/rocksdb-query.git
  commit: e34aca0fe90264dd9aa62d0e081e6e7f4e3a8559
- rocksdb-haskell-1.0.1
- murmur3-1.0.3
- secp256k1-0.5.3
