resolver: lts-16.0
nix:
  packages:
    - rocksdb
    - secp256k1
    - zlib
    - pkg-config
extra-deps:
  - github: jprupp/nqe
    commit: acbed8c6f39055b33e9c24de3ce634cfc2d8de88
  - github: haskoin/haskoin-core
    commit: d313ac58b2f22fa7570a5e1234244b7249a48382
  - github: haskoin/secp256k1-haskell
    commit: 239159122cc6f830957759a1d247ded7ffeba915
  - github: jprupp/rocksdb-haskell
    commit: e138bd26f6048c03f486da2f8a7e3d0e72f5adc0
  - github: jprupp/rocksdb-query
    commit: ee49d29d502e137e2e5cbf9f71a26a71ce04ed8d
