resolver: lts-12.12
nix:
  packages:
    - rocksdb
    - secp256k1
    - zlib
extra-deps:
  - rocksdb-haskell-1.0.1
  - murmur3-1.0.3
  - secp256k1-haskell-0.1.3
  - nqe-0.6.1
  - haskoin-core-0.8.1
  - rocksdb-query-0.2.0
